### ISSUE TITLE
Implement Necessities for Skyline/Arcropolis Smash Ultimate Modding

### ISSUE THREAD

**Issue by tdkcarrion** [Ryujinx/Ryujinx#2230]
#### Overview:
- Implement a way for Skyline (https://github.com/skyline-dev/skyline) & ARCropolis (https://github.com/Raytwo/ARCropolis) (skyline plugin) to work with Smash Ultimate on Ryujinx.

#### Required changes:

- [x] Support memory aliasing: #2954 
- [x] Code memory syscalls: #2958 
- [x] GetProcessID atmosphere extension: #2966 

Further work:

- [ ] Implement the web applet for further compatibility: https://github.com/Ryujinx/Ryujinx/issues/1004

#### Nature of Request:  
- Addition

### Why would this feature be useful?
It is well known that Ultimate Mod Manager (UMM) can work with both Yuzu and Ryujinx, however it is becoming way more outdated, and most SSBU mods are made, or are now being made, for ARCropolis use only. I'm sure that since the community is growing, Smash players such as myself would love to use whatever mod they desire without it being broken by an outdated mod manager such as UMM.

**Comment by tech-ticks** [comment]
Are there any updates on this? The changes required to run Skyline are implemented in https://github.com/Ryujinx/Ryujinx/pull/2451, but PR is not finished and seems to be inactive.

**Comment by MutantAura** [comment]
Closed by #2966

**Comment by gdkchan** [comment]
Web applet is still not supported, so ARCropolis can't be "fully" used. Not sure if this request can be considered fullfilled or not.

**Comment by MutantAura** [comment]
A separate issue for the web applet is already open here: https://github.com/Ryujinx/Ryujinx/issues/1004
These would be duplicates at this moment in time no?

**Comment by gdkchan** [comment]
> A separate issue for the web applet is already open here: #1004 These would be duplicates at this moment in time no?

I think this one can be an "umbrella" issue since this requires multiple different things implemented to work. Not the only one missing AFAIK is offline web applet.

**Comment by TemDevz** [comment]
this would be nice to have for the Steve mods
