### ISSUE TITLE
LDN upstreaming roadmap

### ISSUE THREAD

**Issue by TSRBerry** [Ryujinx/Ryujinx#4716]
It's been a few years since the LDN build was created and in order to open source it completely, we need to upstream all the changes in smaller pieces.

I'm mostly creating this issue to be more transparent about the progress we've been making and how much still needs to be done. It will also help to keep me accountable, so I keep working on LDN and don't prioritize other issues.

## Website

- [ ] Separate the website from the LDN server (status: **In progress**)
- [ ] Get the website ready and open source it (status: **To do**)

## Sockets service

- [ ] Proxy socket support (required for RyuLdn)

## LDN service

- [ ] Change the RyuLdn protocol to use UDP and increment the version (status: **In progress**)
    - (This is the blocking issue we are currently working on internally and is also the reason this is taking so long.)
- [ ] `IUserLocalCommunicationService` (ldn:u) implementation
    - This will also contain the `INetworkClient` interface and the `LdnDisabledClient` implementation

### Network clients

- [ ] ldn_mitm
    - Support for the [ldn_mitm](https://github.com/spacemeowx2/ldn_mitm) sysmodule by @spacemeowx2
- [ ] RyuLdn
    - Our own LDN network client implementation

---

There are also some refactorings and other small things which aren't listed here, but this is usually something we do while we get the upstream PRs ready.
